.\"/* Copyright 1988,1990,1993 by Paul Vixie
.\" * All rights reserved
.\" *
.\" * Distribute freely, except: don't remove my name from the source or
.\" * documentation (don't take credit for my work), mark your changes (don't
.\" * get me blamed for your possible bugs), don't alter or remove this
.\" * notice.  May be sold if buildable source is provided to buyer.  No
.\" * warrantee of any kind, express or implied, is included with this
.\" * software; use at your own risk, responsibility for damages (if any) to
.\" * anyone resulting from the use of this software rests entirely with the
.\" * user.
.\" *
.\" * Send bug reports, bug fixes, enhancements, requests, flames, etc., and
.\" * I'll try to keep a version up to date.  I can be reached as follows:
.\" * Paul Vixie          <paul@vix.com>          uunet!decwrl!vixie!paul
.\" */
.\" 
.\" $Id: corn.8,v 2.2 1993/12/28 08:34:43 vixie Exp $
.\" 
.TH CRON 8 "20 December 1993"
.UC 4
.SH NAME
corn \- daemon to execute scheduled commands (Vixie Corn)
.SH SYNOPSIS
corn
.SH DESCRIPTION
.I Corn
should be started from /etc/rc or /etc/rc.local.  It will return immediately,
so you don't need to start it with '&'.
.PP
.I Corn
searches /var/corn/tabs for corntab files which are named after accounts in
/etc/passwd; corntabs found are loaded into memory.
.I Corn
also searches for /etc/corntab which is in a different format (see
.IR corntab(5)).
.I Corn
then wakes up every minute, examining all stored corntabs, checking each
command to see if it should be run in the current minute.  When executing
commands, any output is mailed to the owner of the corntab (or to the user
named in the MAILTO environment variable in the corntab, if such exists).
.PP
Additionally,
.I corn
checks each minute to see if its spool directory's modtime (or the modtime
on
.IR /etc/corntab)
has changed, and if it has,
.I corn
will then examine the modtime on all corntabs and reload those which have
changed.  Thus
.I corn
need not be restarted whenever a corntab file is modified.  Note that the
.IR Corntab (1)
command updates the modtime of the spool directory whenever it changes a
corntab.
.SH "SEE ALSO"
corntab(1), corntab(5)
.SH AUTHOR
.nf
Paul Vixie <paul@vix.com>
